<template>
    <p>GitHub Copilot was used to generate an initial simple Minesweeper game for my infinisweeper application, as well as for inline code suggestions throughout the development process of the website. No text or images were generated by an LLM.</p>
</template>